import sqlite3
conn = sqlite3.connect('library.db')
c= conn.cursor()
print("######MEMBERS##########\n")
c.execute("SELECT * FROM members")
rowsM = c.fetchall() 
for row in rowsM: 
    print('MEMBER -->',end='')
    print(row)
print("######BORROWINGS##########\n")
c.execute("SELECT * FROM borrowings")
rowsB= c.fetchall() 
for row in rowsB: 
    print('BORROWING -->',end='')
    print(row)
print("######Penalties##########\n")
print('\n')
c.execute("SELECT * FROM penalties")
print(c.fetchall())
print('\n')
print("#######REVIEWS##########")
c.execute("Select * FROM reviews")
print('\n')
print(c.fetchall())
conn.close()