import sqlite3
conn = sqlite3.connect('library.db')
c= conn.cursor()
c.execute("SELECT * FROM members")
print(c.fetchall())
print("\n")
c.execute("SELECT * FROM borrowings")
print(c.fetchall())
print("######Penalties##########\n")
print('\n')
c.execute("SELECT * FROM penalties")
print(c.fetchall())
print('\n')
print("#######REVIEWS##########")
c.execute("Select * FROM reviews")
print('\n')
print(c.fetchall())
conn.close()